name: Example Workflow

on:
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run a simple command (e.g., printing Hello World)
      - name: Print Hello World
        run: echo "Hello, World!"

      # Step 3: Run additional commands or scripts
      - name: Run a script
        run: |
          echo "This is an example script step"
          echo "You can add your commands here"
